//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdsoftEntities : DbContext
    {
        public bdsoftEntities()
            : base("name=bdsoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Asistencias> Asistencias { get; set; }
        public virtual DbSet<DetalleDeAsistencias> DetalleDeAsistencias { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<EquiposTecnologicos> EquiposTecnologicos { get; set; }
        public virtual DbSet<LogTablas> LogTablas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
